project:
  type: website

website:
  title: "Emma's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/emmarvalle1

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


